## The following tables/csv files will be created after running this notebook:
Product

This script reads the product.csv and cleans the rating as well the categories. It overwrites the originall Product.csv.

The original schema contains: 'uniq_id','Product_Name','Manufacturer','Price','average_review_rating','amazon_category_and_sub_category','description'


The new schema contains:
'uniq_id','Product_Name','Manufacturer','Price','average_review_rating','cat1','cat2','cat3','description'

In [27]:
import pandas as pd
import numpy as np

In [28]:
df = pd.read_csv("product.csv")

In [29]:
df.head()

,Unnamed: 0,uniq_id,Product_Name,Manufacturer,Price,average_review_rating,amazon_category_and_sub_category,description
0,0,0016eb63fa6c7a5e8930bc7732b13116,Resident Evil 6 Play Arts Kai Helena Harper Ac...,Unknown,49.88,5.0 out of 5 stars,Figures & Playsets > Science Fiction & Fantasy,Product Description From Square Enix! From the...
1,1,00182f9b6081e58fea1fe76bc13eb022,Disney Frozen Musical and Light-Up Elsa Fancy ...,George,24.99,4.3 out of 5 stars,Characters & Brands > Disney > Toys,"LET IT go, let it go, cant hold it back any mo..."
2,2,0030f5965cbd07a138147425b9a0156c,Disney The Lion King Childrens 24 Piece Simba ...,King International,6.53,5.0 out of 5 stars,Characters & Brands > Disney > Toys,NaN
3,3,0034d77b68130bba71aca6e733c7e1ac,Pokemon Black and White Voice Activated Talkin...,Takara Tomy,30.23,5.0 out of 5 stars,Characters & Brands > Tomy,Pokemon Black and White Voice Activated Talkin...
4,4,0039295c7fcefba10d5fc333eff806d3,LEGO City Airport 60022: Cargo Terminal,LEGO,199.18,4.7 out of 5 stars,NaN,Product Description Get busy loading the cargo...

In [30]:
def clean_rating(x):
    if (type(x)==str):
        score,*_ = x.split(" ")
        return float(score)
def clean_average_review_rating(df):
    df["average_review_rating"] = df["average_review_rating"].apply(lambda x:clean_rating(x))
    return df

In [31]:
df = clean_average_review_rating(df)

In [25]:
def process_category_value(x,cat1,cat2,cat3):
    '''
    if x is null, all 3 categories are "All"
    if x has more than 3 categories, only first 3 categories are kept and assigned to 
        cat1, cat2, cat3.
    if x has less than 3 categories, "All" will be appended as needed
    '''
    default = ["All","All","All"]
    if (x == x):
        all_categories = x.split(" > ")
        for i in range(len(all_categories)):
            default[i] = all_categories[i]
            if (i == 2):
                break;
    
    cat1.append(default[0])        
    cat2.append(default[1])
    cat3.append(default[2])

def process_category_columns(df):
    '''
    create 3 empty lists and apply process_category_value.
    append 3 new columns to df and drop the orignal category column
    '''
    cat1 = []
    cat2 = []
    cat3 = []
    df.amazon_category_and_sub_category.apply(lambda x:process_category_value(x,cat1,cat2,cat3))
    df["Cat1"] = cat1
    df["Cat2"] = cat2
    df["Cat3"] = cat3
    df.drop(columns = "amazon_category_and_sub_category",inplace = True)
    return df

In [32]:
df = process_category_columns(df)

In [34]:
df.head()

,Unnamed: 0,uniq_id,Product_Name,Manufacturer,Price,average_review_rating,description,Cat1,Cat2,Cat3
0,0,0016eb63fa6c7a5e8930bc7732b13116,Resident Evil 6 Play Arts Kai Helena Harper Ac...,Unknown,49.88,5.0,Product Description From Square Enix! From the...,Figures & Playsets,Science Fiction & Fantasy,All
1,1,00182f9b6081e58fea1fe76bc13eb022,Disney Frozen Musical and Light-Up Elsa Fancy ...,George,24.99,4.3,"LET IT go, let it go, cant hold it back any mo...",Characters & Brands,Disney,Toys
2,2,0030f5965cbd07a138147425b9a0156c,Disney The Lion King Childrens 24 Piece Simba ...,King International,6.53,5.0,NaN,Characters & Brands,Disney,Toys
3,3,0034d77b68130bba71aca6e733c7e1ac,Pokemon Black and White Voice Activated Talkin...,Takara Tomy,30.23,5.0,Pokemon Black and White Voice Activated Talkin...,Characters & Brands,Tomy,All
4,4,0039295c7fcefba10d5fc333eff806d3,LEGO City Airport 60022: Cargo Terminal,LEGO,199.18,4.7,Product Description Get busy loading the cargo...,All,All,All

In [35]:
df.to_csv("product.csv")